DROP TABLE IF EXISTS fios, doctors, patients, tickets;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS fios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  patronymic VARCHAR(100) NOT NULL,
  CONSTRAINT pk_fio PRIMARY KEY (id),
  CONSTRAINT uq_fios_for_first_name_last_name_patronymic UNIQUE (first_name, last_name, patronymic)
);

CREATE TABLE IF NOT EXISTS doctors (
  --id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  --personnelNumber INTEGER,
  id UUID NOT NULL,
  --fio_id INTEGER NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  patronymic VARCHAR(100) NOT NULL,
  specialization VARCHAR(255) NOT NULL,
  start_work TIME WITHOUT TIME ZONE,
  end_work TIME WITHOUT TIME ZONE,
  CONSTRAINT pk_doctor PRIMARY KEY (id)
  --CONSTRAINT fk_doctor_for_fio FOREIGN KEY (fio_id) REFERENCES fios (id)
);

CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cart_number UUID DEFAULT UUID_GENERATE_V4 (),
  --fio_id INTEGER NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  patronymic VARCHAR(100) NOT NULL,
  birthday date NOT NULL,
  --cartNumber INTEGER NOT NULL,
  parcelNumber INTEGER NOT NULL,
  CONSTRAINT pk_patient PRIMARY KEY (id)
  --CONSTRAINT fk_patient_for_fio FOREIGN KEY (fio_id) REFERENCES fios (id)
);

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  --doctor_id BIGINT NOT NULL,
  --patient_id BIGINT NOT NULL,
  start_time TIMESTAMP WITHOUT TIME ZONE,
  end_time TIMESTAMP WITHOUT TIME ZONE,
  ticket_status VARCHAR(255) NOT NULL,
  CONSTRAINT pk_ticket PRIMARY KEY (id)
  --CONSTRAINT fk_ticket_for_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
  --CONSTRAINT fk_ticket_for_patient FOREIGN KEY (patient_id) REFERENCES patients (id)
);

