name: CI/CD
on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование кода репозитория
        uses: actions/checkout@v3
      - name: Установка java 17-ой версии с maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Сборка проекта и тестирование
        run: mvn clean install
